version: "2"
services:
        chopshop:
                build: ./chopshop
                ports:
                        - "4242:4242"
        carracing:
                build: ./carracing
                ports:
                        - "5000:5000"
